serve:
  port: 8080
  servlet:
    context-path: "/bootcamp"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://yxkywvmqnrgwbh:f53a056bee6e8ff933bd876e5f26abc7283d72398199bad069ba817d032a7547@ec2-52-23-45-36.compute-1.amazonaws.com:5432/dbas4glk118lr
    username: yxkywvmqnrgwbh
    password: f53a056bee6e8ff933bd876e5f26abc7283d72398199bad069ba817d032a7547
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend

